dnl Written by Lohann Paterno Coutinho Ferreira.

AC_INIT([example01], [0.1.0], [developer@lohann.dev])
AC_CONFIG_AUX_DIR(tools)
AM_INIT_AUTOMAKE([foreign -Wall -Werror])

# AC_CHECK_HEADER([printf.h], [HAVE_BZIP2_H=1], [HAVE_BZIP2_H=0])

AC_PROG_CC
AC_CONFIG_HEADERS([config.h])
AC_CONFIG_FILES([Makefile src/Makefile])
AC_OUTPUT
